version: '3.8'
services:
  nl-www:
    image: php:7.4-apache
    container_name: nl-www
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./www:/var/www/html
    environment:
      - COD2_SERVER1_ADDRESS=mynl.pl
      - COD2_SERVER1_PORT=7
      - COD2_SERVER2_ADDRESS=mynl.pl
      - COD2_SERVER2_PORT=6
